CoaguCo-Industries/GodotSteam

godotsteam/godotsteam.cpp, godotsteam/godotsteam.h
Note: I've removed the updateLeaderboardHandle since it's no longer necessary. Now this will work as the Steamworks docs explain, that is just call findLeaderboard and you're ready to use the leaderboard functions.
=> Fixed _leaderboard_loaded types and removed updateLeaderboardHandle function

godotsteam/godotsteam.cpp
Image.lock() must be called before using Image.set_pixel() or Godot will throw an error. 
Print to console about avatar_loaded signal not emitting
=> Lock avatar image before writing

godotsteam/godotsteam.cpp, godotsteam/godotsteam.h
In the Steam API, the getAchievement and getAchievementAndUnlockTime functions use pointers to return the information requested, the actual functions return a bool indicating success of the function.  I modified the functions to return a dictionary with the return value from the function and the data requested.
=> Fix some functions that returned data via pointer

godotsteam/config.py
This should keep things consistent with SCons, see this issue on the Godot repo https://github.com/godotengine/godot/issues/22195 
Same error but with the GodotSteam module instead of ARVR.
=> can_build() now takes 1 argument instead of 2

godotsteam/godotsteam.cpp, godotsteam/godotsteam.h
The function `uploadLeaderboardScore` now has a third argument to be able to pass details to the leaderboards.
Also use `setLeaderboardDetailsMax` before calling `getLeaderboardEntries` to include details on the array.
=> Added the possibility to upload/download details for Leaderboards

godotsteam/godotsteam.cpp
After playing around with this, it felt like it would be a good idea to have the Steam ID of the avatar owner included.  This way you don't have to have variables scoped outside the method to track and handle these if you want to do some additional work.
=> Adding steamID to the avatar loaded signal.

godotsteam/godotsteam.cpp, godotsteam/godotsteam.h
So, just added back the JoinGameRequest which uses GameRichPresenceJoinRequested_t. Should work fine, it's just like it was before. So now we have JoinGameRequest and JoinRequest Callbacks, first one is for running games and second for lobbies #60
=> Added JoinGameRequested

include/godotsteam.h, src/godotsteam.cpp
Small additional utility method for getting number of lobby members. Can be used, for example, to sort out already full lobbies that cannot accept new players at the moment.
=> Added getNumLobbyMembers method

include/godotsteam.h, src/godotsteam.cpp
Actually, the corresponding methods already were present in the code, but one additional step was required to make it work:
`callEnteredLobby.Set(hSteamAPICall, this, &Steam::_lobby_joined);`
Also, I've added one additional parameter to the lobby_joined signal, which slightly simplifies gdscript code (one boolean check connection_failure instead of need to inspect the values of response)
=> lobby_joined signal

include/godotsteam.h, src/godotsteam.cpp
Important hotfix for my previous pull request, I've mistaken with function syntax, ReadP2PPacket() function actually can return Steam ID of the user who sent the packet to us, so it is not required to pass steamIDRemote parameter.
Also, resulting array can be shrinked to the size of bytes actually read with the help of bytesRead varialble.
=> readP2PPacket() fix

.gitignore, SConstruct, VisualC/GodotSteam.sln, VisualC/GodotSteam.vcxproj, VisualC/GodotSteam.vcxproj.filters, VisualC/GodotSteam.vcxproj.user, src/godotsteam.cpp
I've added flags for static linking we discussed... You said that library works on Linux when you compiled it yourself, maybe this flags helped too :)
Also I've changed linker flags for Windows with the same purpose, namely I've replaced /MD with /MT and /MDd with /MTd. As I've said, this helped to fix library on my friend's machine.
Please note, that you should change this flags for GodotNativeTools/godot-cpp too when compiling.
Another small change: I've removed fetching of custom lobby member data "ready" from the function getLobbyMembersData(). This code was copy-pasted by me from the Valve example application SpaceWar and it is really not needed, Anyway, getLobbyMembersData() returns you steamIDLobbyMember, therefore you can later call GetLobbyMemberData().
The last feature here is …
=> Static linking + code cleaning + Visual Studio solution

godotsteam/godotsteam.cpp
In the current state of `godot2` branch the build throws 2 errors like the following:
```
modules/godotsteam/godotsteam.cpp:3175:135: error: conversion from 'Steam::(anonymous enum at modules/godotsteam/godotsteam.h:14:3)' to 'const Variant' is ambiguous
ObjectTypeDB::bind_method(_MD("downloadLeaderboardEntries", "range_start", "range_end", "type"), &Steam::downloadLeaderboardEntries, DEFVAL(GLOBAL));
```
In the `master` branch therese errors are fixed, parsing the enum variables to `int`. This PR applies the same solution to branch `goto2`.
=> fix: cast enum value to int

godotsteam/config.py
Add a flag for the c++ compiler in osx tu use C++11, which is requried to compile `nullptr`. Withous this, the build process fails because MacOS uses the default g++ version, which is 10.
:point_right:  This should be applied to all version branches.
=> fix(complire): add osx compiler flag to use c++11

SConstruct, src/godotsteam.cpp
Two small commits to improve GodotSteam experience :)
1) I've added lobby owner ID and friend relationship of lobby owner with the current user.
Using this information we can filter lobbies later in code (to show, for example, lobbies only created by friends of the current user or filter out lobbies created by someone who is on blacklist and so on)
2) Small fix in SConstruct file, without that the library crashes on start (I've copied this from Linux part of the build file and it helped)
3) Small fix for success parameter for some signals: due to misprint there is no ! sign, therefore the value of the parameter was wrong. I heard that this was fixed in the master branch, but it looks like it was not fixed in the gdnative branch.
=> Friend relationship for lobby owner + OSX build fix

godotsteam/config.py
Added a macos compiler flag to fix a nullptr issue during compilation, full credit to @guillem-sopra
This has already been fixed for the godot2 branch but for some reason was not yet added to the godot3 branch.
=> [macos] Fix nullptr issue during compilation.

include/godotsteam.h, src/godotsteam.cpp
Some more code for Steam lobbies :)
1) RequestLobbyData method
2) AddRequestLobbyListDistanceFilter method
If AddRequestLobbyListDistanceFilter is not called, k_ELobbyDistanceFilterDefault will be used, which will only find matches in the same or nearby regions.
3) GameLobbyJoinRequested_t callback, to be able to handle Invites from the other users
=>  RequestLobbyData, AddRequestLobbyListDistanceFilter and GameLobbyJoinRequested_t callback

godotsteam/config.py
Fixes #105 
Today when compiling against Steamworks SDK `v1.46`, I encountered a link error and
figured out that Steamworks SDK actually renamed `sdk/redistributable_bin/osx32` to `sdk/redistributable_bin/osx`.
Using this version, I was able to successfuly compile against `v1.46`
=> Rename sdk/redistributable_bin/osx32 to sdk/redistributable_bin/osx

godotsteam/godotsteam.cpp
Currently getAuthSessionTicketID  doesn't put the buffer into a PoolByteArray, thus the buffer entry in the dictionary returns "True", this fixes this and returns the actual data necessary for authentication.
=> Make getAuthSessionTicketID return the ticket buffer

godotsteam/mingw_patch.py
- brought up in #120 
- pending approval/testing from @zombieCraig
- remove newline that I thought was normalized by python and blocked correct behavior in windows
=> remove unnecessary newline breaking expected text in patch script

godotsteam/godotsteam.cpp
Solves an issue that caused getqueryugcresult to not handle UTF-8 characters in titles and descriptions of UGC items.
=> Fix getQueryUGCResult not handling UTF-8 characters properly

godotsteam/godotsteam.cpp
Fixes compiler warnings that show up in macOS / Clang.
Also fixes a mistake in a comparative function.
=> Fix compiler warnings on MacOS / Clang

godotsteam/godotsteam.cpp
I realised that String::utf8 exists, this seems to work fine on Windows unlike the previous solution.
=> Use String::utf8 instead of charToWChar in getQueryUGCResult

godotsteam/doc_classes/Steam.xml, godotsteam/godotsteam.cpp
I've written documentation for select P2P functions, constants, and signals that includes descriptions for members and names for arguments. The descriptions were taken from Steam's documentation and were rewritten and summarized to fit within Godot's terminology, and to improve clarity. I also have plans to add documentation for other members like achievements and cloud saving if my effort is wanted.
Functions:
acceptP2PSessionWithUser
allowP2PPacketRelay
closeP2PChannelWithUser
closeP2PSessionWithUser
getP2PSessionState
getAvailableP2PPacketSize
readP2PPacket
sendP2PPacket
Signals:
p2p_session_request
p2p_session_connect_fail
Constants:
P2P_SEND_UNRELIABLE
P2P_SEND_UNRELIABLE_NO_DELAY
P2P_SEND_RELIABLE
P2P_SEND_RELIABLE_WITH_BUFFERING
P2P_SESSION_ERROR_NONE …
=> Added documentation to select P2P functions, constants, and signals

godotsteam/godotsteam.cpp
I noticed that the setAchievement function wouldn't actually return false if an achievement name that doesn't exist within the App Admin was passed in. This commit changes that so the function will return false in that scenario just as it would in the Steam API.
=> Fix to setAchievement return statement

godotsteam/doc_classes/Steam.xml
The new docs for the achievement functions incorrectly identified
user_stats_stored as the callback for requestCurrentStats. This has been
corrected to use current_stats_received.
=> Fixed docs using user_stats_stored in place of current_stats_received

godotsteam/godotsteam.cpp
Makes setItemDescription use k_cchPublishedDocumentDescriptionMax as stated in the docs: https://partner.steamgames.com/doc/api/ISteamUGC#SetItemDescription
=> Make setItemDescription use k_cchPublishedDocumentDescriptionMax

tutorials-lobbies-p2p.html
Found a couple bugs when following through the tutorial.
These fixes should help:
ByteArray should be converted and stored and a Dictionary as output from `bytes2var` instead of PoolByteArray
Typo in argument delimiter should be `,` instead of `:`
=> Fixed code typos in lobby tutorial

godotsteam/SCsub, godotsteam/config.py
I've started moving the modules that I use in Godot projects to be in the source code (and Git repo) for the game project itself (for example, in a `godot-modules/` directory), and then building Godot like `scons custom_modules=.../my-game-project/godot-modules`.
This is nice for keeping things organized: I have all the source for all the modules my games depend on in my game's source code, including any custom modules that I made for that game. It has also allowed me to setup CI to build Godot for games that need custom modules.
Anyway, for most modules, this just works! However, with GodotSteam, it doesn't, because it's using paths relative to the Godot source directory (ie. `env.Append(CPPPATH=["#modules/godotsteam/sdk/public/"])` with the `'#'` at the front of the path) to find the …
=> Allow building with 'scons custom_modules=...'

godotsteam/godotsteam.cpp
- Return submitted boolean
- Make it use String::utf8
- Add PropertyInfos to the gamepad_text_input_dismissed signal
Should help for Steam on Deck later this month
=> Various gamepad_text_input_dismissed fixes

tutorials-lobbies-p2p.html
- Session connect fail's first argument is Steam id:
https://partner.steamgames.com/doc/api/ISteamNetworking#P2PSessionConnectFail_t
- _send_P2P_Packet requires both target and packet data
=> Fix networking documentation typos

godotsteam/godotsteam.cpp
`call_data->m_nAppID` is being incorrectly cast to `AppId_t`, which is the type it already is.
It should be cast to `uint32_t`.
=> fix: use correct cast

godotsteam/godotsteam.cpp
Hello! According to [API](https://partner.steamgames.com/doc/api/ISteamMatchmaking#LobbyChatMsg_t) `_lobby_message` should return `lobby_id`.
BTW Thanks for your awesome work! :)
=> Fix _lobby_message signal

godotsteam/godotsteam.cpp
Fixes receive message functions to allow for more than 1 message at a time
I was playing around with the SteamNetworkingMessage functions and was getting a crash when calling receivingMessagesOnChannel() with max_messages > 1
Not sure if it was the same error as described in https://github.com/Gramps/GodotSteam/pull/243#issue-1195317769
I have only tested receiveMessagesOnChannel() and not the NetworkingSockets functions receiveMessagesOnConnection() and receiveMessagesOnPollGroup(), but they behave the same way
=> Fix receive message functions

godotsteam/godotsteam.cpp, godotsteam/godotsteam.h
Previously, the children dictionary entry in getQueryUGCChildren would be a bool, this is because it used to try to simply set the dictionary entry to a raw pointer, which would cause it to be interpreted as a bool when converting it to a Variant.
The only caveat is that it requires knowing the child count ahead of time, but this is what steam expects anyways.
=> Fix getQueryUGCChildren not working at all

.github/workflows/build-linux-artifact.yml, .github/workflows/build-osx-artifact.yml, .github/workflows/build-releases.yml, .github/workflows/build-windows-artifact.yml
This PR adds automated builds for Win64 (editor, release template and debug template), Linux64 (editor, release template, debug template) and Linux64 Headless (editor).
It requires the Steamworks SDK in order to compile GodotSteam properly. You will need to add that to a private repo and tag the versions appropriately. I have tested it locally with the tag  "153a" on the private JDare/Steamworks-SDK repo. You will also need to add a Personal Access Token which has access to that repo in order to pull its contents at build time. These should be added as the following secrets to this repo:
STEAMWORKS_SDK_REPO: Gramps/Steamworks-SDK (or whatever you call it)
STEAMWORKS_SDK_REPO_TOKEN: <your personal access token>
To bump dependencies in the future you can simple edit the env parameters at …
=> Adding build workflows for win64, linux64

tutorials-achievement-icons.html, tutorials-avatars.html
As of Godot 3.X.Y, Images are able to be built directly in a much more performant manner by directly calling `create_from_data(height, width, use_mipmaps, format, buffer)`. This PR changes the tutorial code to reflect this, enabling users of the tutorial to have faster construction of player Avatars and Achievement Icons, which were a point of performance issues when large lobbies were connected to (> 10 players).
=> Update texture construction code in documentation

godotsteam/doc_classes/Steam.xml, godotsteam/godotsteam.cpp, godotsteam/godotsteam.h
SteamAPI::GetLocalPingLocation return the age of the data and edit (by reference)
the result SteamNetworkPingLocation_t which contains the location.
From Steam point of view, a location is an array of 512 bytes-length.
This is an opaque item that can be changed to String to be sent over network and
deserialized by after.
The commit changes all methods that uses location to take the location structure:
getLocalPingLocation
estimatePingTimeBetweenTwoLocations
estimatePingTimeFromLocalHost
convertPingLocationToString
parsePingLocationString
=> update locations data structure

godotsteam/godotsteam.cpp
Steam API allows passing `NULL` in to `SubmitItemUpdate` to provide no note. https://partner.steamgames.com/doc/api/ISteamUGC#SubmitItemUpdate
=> Provide no change note when empty

godotsteam/doc_classes/Steam.xml
As discovered in release `g351-s155-gs3175`, when migrating from `g344-s154-gs3161`, the signature for the following leaderboard callback functions have changed, inserting a new (welcome) leaderboard handle parameter. This PR updates the docs to reflect the new signature.
* `leaderboard_score_uploaded`
* `leaderboard_scores_downloaded`
Edit: Signature updates occurred here: https://github.com/Gramps/GodotSteam/commit/8f29493f3bf1326171cb97eafe155dbc36e2f621
=> Update leaderboard callback signatures in docs

godotsteam/godotsteam.cpp
Parameters can't have spaces in their names.
This was causing Godot 4.0 .NET compilation to fail because it generated an event delegate with the parameter name "io failure" which is not valid because it contains a space.
In 3.x signals are not generated in C# so it doesn't really matter but spaces are still not valid in identifiers as far as I'm concerned so it's probably a good idea to avoid them.
=> Fix `io_failure` param name in `steamworks_error` signal

addons/godotsteam/godotsteam.gdnlib
Wrong path for the steam_api64.dll dependency causes Windows export to fail.
=> Fix wrong path breaking windows export.

godotsteam.cpp, godotsteam.h
This should help avoid some naming conflicts when building with the .NET module.
Also, it makes the API use the enum types instead of ints so users get a better idea of what values are expected to be used.
I also found that `MARKETING_MESSAGE_FLAGS_PLATFORM_RESTRICTIONS` was missing its value so I fixed it here but probably needs to be backported to 3.x too.
When choosing whether the type should be an enum or a bitfield flag I chose based on the enum values but since I'm not very familiar with Steam's API maybe some of them don't make sense as bitfield flags. Let me know if I made a mistake 🙇.
=> Bind enums as real enums or bitfield flags

.gitignore, .gitmodules, SConstruct, godotsteam.gdextension, godotsteam/godotsteam.cpp, godotsteam/godotsteam.h, godotsteam/init.cpp
Can't say I've rigorously tested it, but it seems to work at least in some way, i.e. calling steamInit works. To test it, I copied the bin directory + the gdextension file to `addons/godotsteam` and put the dynamic steam library in that same `bin` directory. I presume when shipped as an addon all the steam libraries should be there together.
Had to replace exposed integer types less than int32, because those no longer work when registering with ClassDB.
Also added godot-cpp as a submodule.
=> Godot 4 GDExtension port

.github/workflows/build-mac-plugin.yaml, SConstruct
This PR adds in CI which will compile a universal library for macOS for the plugin version of GodotSteam. Following this PR, more CI to build the windows and linux plugins will be added, but for now as this is the 'least updated' version of the plugin, it was figured this was most in need.
=> Compile universal library for macOS. 

README.md, SConstruct, godotsteam.gdextension
After actually trying to automate this, I noticed that it would be helpeful to
- Copy the steam library to bin automatically
- Make the gdextension depend on the steam libraries so they're copied to the build dir automatically. The syntax of dependencies is `{ "original path": "build dir path" }`, not sure if it's right on MacOS but otherwise it works.
=> Make SCons copy the steam library to bin, add dependency to gdextension

godotsteam.cpp
I was trying to work with the `createListenSocketP2P` for Steam's SteamNetworkingSockets and was running into an issue where my game would instantly crash whenever the method was called. After debugging it a little bit, I was able to narrow in on the length of the options array being passed was using the `sizeof(options)` to determine number of options passed. This sizeof returns an incorrect number of options, as that is the full Array object size, rather than the length of the internal Array. I swapped the sizeof to use Array's `size()` method and this fixed the crashes I was observing.
I also noticed that one of the GodotSteam network wrapper functions was correctly cleaning up the allocated Options array, but the other instances did not. I converted all of these non-conformant …
=> Godot4: SteamNetworking fixes for options array size and memory leaks.

.github/workflows/build-releases.yml, README.md, SCsub
This lets users skip the LD_LIBRARY_PATH workaround script.
If a Linux binary (or library) has an rpath that includes `$ORIGIN`, it will look in its own directory for linked libraries. (i.e. it will act as if `LD_LIBRARY_PATH=$MYDIR` was set. All automatically!
Here's an [article](https://nehckl0.medium.com/creating-relocatable-linux-executables-by-setting-rpath-with-origin-45de573a2e98) about it.
By setting this rpath value, you should be able to drop the Linux caveat warnings about finding libsteam_api.so and also basically drop the `godotsteam.sh` wrapper.
That said, I did not change any documentation around Linux caveats yet (I imagine a similar change should happen in the plugin branches as well first, plus maybe a release or two to give folks times to upgrade).
I also didn't remove …
=> Set an $ORIGIN rpath for the Linux editor

SConstruct
This helps it find libsteam_api.so
(This gdnative plugin does have the same problem the editor does -- this is how I actually originally noticed the problem.)
Related to https://github.com/Gramps/GodotSteam/pull/317
=> Set an $ORIGIN rpath for the Linux plugin

docs/howto_gdextension.md
- updates docs for building the GodotSteam GDExtension on macOS
- replaces example GDScript with valid code
=> docs: fix docs for macos

.github/workflows/build-gdextension.yml, .github/workflows/build-releases.yml, .gitignore, SConstruct, godotsteam.gdextension
Resolves #355
- Added github actions for gdextension to help with MacOS builds. This also adds support for 32 bit platforms via gdExtension. 
- Removed the api.json as its redundant with godot-cpp as a submodule checked out to the correct version. 
- Updated godot-cpp to v4.1-stable
- Changed .gdextension to use relative path to make the add-on portable in file structure placement.
=> Add Github actions

.github/workflows/build-gdextension.yml
Small change to add a `.gdignore` file to the bin folders so they do not show in the editor.
=> Add .gdignore file to bin folders
