CoaguCo-Industries/GodotSteam

- godotsteam/godotsteam.cpp
- godotsteam/godotsteam.h
As seen in https://partner.steamgames.com/doc/api/steam_api#SteamAPI_RestartAppIfNecessary
> Add SteamAPI_RestartAppIfNecessary

- godotsteam/config.py
- godotsteam/godotsteam.h
Fix wrong argument to compile OSX under linux
Fix missing symbols when compiling under linux
> Small fixes for compilation

- godotsteam/godotsteam.cpp
- godotsteam/godotsteam.h
I've also renamed the int32 to int32_t as you did on the master branch.
> Fixed getFileTimestamp and getSteamID return types

- godotsteam/godotsteam.cpp
- godotsteam/godotsteam.h
> Fixed JoinRequested Signal

- SConstruct
- include/godotsteam.h
- src/godotsteam.cpp
These commits contain fixes for https://github.com/Gramps/GodotSteam/issues/57 , as well as some improvements:
- Added method for initializing Steam Server
- Added methods for getting/setting lobby data
- Added stubs for some methods that caused compile errors
- Fixed SConstruct file to be able to compile against the most recent GodotNativeTools
- Fixed some bugs, added some improvements
> Fix for https://github.com/Gramps/GodotSteam/issues/57 and some improvements

- include/godotsteam.h
- src/godotsteam.cpp
After struggling with UPNP from Godot 3.1 release without success, I've decided to add support for P2P via Steam libraries, and it actually works :)
Look here about the Steam interface I used to achieve this:
https://partner.steamgames.com/doc/api/ISteamNetworking
The workflow for establishing P2P connection is the following:
1) Use sendP2PPacket() method to send the data to Steam user with some ID (you can obtain Steam user's ID, for example, from game lobby)
2) On the target user's machine, p2p_session_request signal is emitted. Target user should respond to this signal with acceptP2PSessionWithUser() and sendP2PPacket() with some data back.
3) On the initial user's machine, p2p_session_request signal is emitted. Initial user should respond to this signal with …
> P2P support

- include/godotsteam.h
- src/godotsteam.cpp
Tried to add friend lobbies support from the repository of @ConnorBP into gdnative branch. Unfortunately, not all code worked for me, so I used the variant of the method which returns the dictionary, it seems to work :)
>  Friend lobbies support

- godotsteam/godotsteam.cpp
- godotsteam/godotsteam.h
I have added the getInputTypeForHandle-method to fetch the controller type.
> added getInputTypeForHandle

- godotsteam/godotsteam.cpp
Haven't worked with C++ in a while but this seems to do what I need it to. Any suggestions to better style is welcome
>  Fix crash on "_lobby_message" callback

- godotsteam/godotsteam.cpp
- godotsteam/godotsteam.h
Added createQueryUGCDetailsRequest
Added getQueryUGCResult
> Added UGC QueryDetailsRequest and get result

- godotsteam/godotsteam.cpp
- godotsteam/godotsteam.h
I'm not sure whether I have made mistake about calling UGC getItemInstallInfo, I couldn't get the right results before.
This is working in my case, even I don't know exactly what is going on. 
Hope it helps!
> Fix getItemInstallInfo

- godotsteam/config.py
- godotsteam/doc_classes/Steam.xml
Known Issue: Argument name does not override.
Still searching for what I missed.
> Added in-editor documentation

- godotsteam/godotsteam.cpp
> Fix for macOS

- godotsteam/godotsteam.cpp
- godotsteam/godotsteam.h
This does not implement proper signals for HTML, with handles and such, but at least now it is somewhat useful.
> HTML bandaind fix

- godotsteam/doc_classes/Steam.xml
- godotsteam/godotsteam.cpp
Updated documentation for `getMostAchievedAchievementInfo`
Created documentation for `getNextMostAchievedAchievementInfo`
Updated documentation templates.
> Updated getMostAchievedAchievement documentation

- games.html
* Also reverse order of I's and K's to be in alphabetical order
* Added missing `</li>` to MMA Simulator
> Add my brother lives in a canyon to game list

- godotsteam/godotsteam.cpp
- godotsteam/godotsteam.h
Do note: some of these APIs are untested since I don't have access to deck hardware or software, but I think they are simple enough to not need much testing at all.
> Upgrade to Steamworks SDK 1.52 & add new Steam Deck specific APIs

- godotsteam/godotsteam.cpp
- godotsteam/godotsteam.h
as that prevented C# build (Godot mono) from succeeding
> Fixed inputInit default value being defined as int when it is a bool

- godotsteam/godotsteam.cpp
Fixes #218
Fixes #219
Fixes #222
> Fix crashes during using different functions

- example/src/examples/lobby-member.gd
- example/src/examples/lobby.gd
This PR updates the code in the example project to reflect the code in the documentation on the website, as well as provide a faster means of creating images for loading avatars/achievements.
> Update example project to reflect latest documentation code

- functions-networking-utils.html
Update signatures of functions related to locations followin commit #2ec075f77bc7b34
> locations documentation update

- tutorials-leaderboards.html
Fixed some syntax
Fixed steamID -> steam_id for leader board download return
> Leaderboard tutorial fixes

- godotsteam/godotsteam.cpp
- Closes https://github.com/Gramps/GodotSteam/issues/281
> Fix `uploadLeaderboardScore` default value

- example/src/examples/lobby-member.gd
- example/src/examples/lobby.gd
fixed in example branch :
- a crash when joining lobby
- an error when a signal is thrown
tyvm for your work Gramps 👍🏼
> Example fixes

- tutorials-lobbies-p2p.html
This PR adds in a brief description of how one can compress the PoolByteArray generated from `var2bytes` in the tutorial to reduce packet size and improve network performance.
> Added documentation about compressing data

- godotsteam.cpp
- godotsteam.h
This PR addresses #302 and provides the flag parameter as needed. See screenshot for example usage.
> [#302] Add in `friend_flags` parameter to getFriendCount()

- .github/workflows/build-macos-artifact.yml
- .github/workflows/build-releases.yml
- .github/workflows/build-windows-artifact.yml
Tested as much as is possible in a fork, further testing needs to be done on the main repo.
Should be fully working.
> Completed Github actions for Godot4 beta releases

- docs/tutorials/friends_lobbies.md
- mkdocs.yml
I'm not sure what I need to do to add it to the left bar if that's necessary.
Idk how useful this tutorial might be, but I figured someone new might need it.
Edit: Link to preview: https://github.com/WAFFO/GodotSteam/blob/gh-pages-source/docs/tutorials/friends_lobbies.md
> Add tutorial page for lobbies with friends in them

- godotsteam.cpp
This PR fixes the Voice functionality in GodotSteam, by first returning a `PoolByteArray` with the compressed data as part of the dictionary (resolving #311 which had it previously returning a bool), and fixing the DecompressVoice function which was previously broken due to the buffer the uncompressed voice would go into having a size of 0 and the wrong pointer being passed in for writing to this PoolByteArray.
The docs will need to be updated to reflect the change in return value, but as this functionality has effectively been broken the whole time, I doubt this is a truly breaking change of the API.
The change in API allows one to do the following:
```
func _process(_delta: float) -> void:
Steam.run_callbacks()
var voice_avail = Steam.getAvailableVoice()
if voice_avail['result'] == 0: …
```
> [#311] Fix GetVoice and DecompressVoice

- godotsteam.cpp
> Fix SteamParamStringArray_t being deleted before submission

- SConstruct
- godotsteam.gdextension
> fix: repair macos builds
